apiVersion: v1
kind: Namespace
metadata:
  name: mlops
  labels:
    project: observability-ml-alerting
    managed-by: kubectl

---
# =============================================================================